### PR TITLE
Add the script that fixes the date strings

### PR DESCRIPTION
**Pull request by icyflame**
@amrav I have checked the script with some static text in a file, but have not been able to check it on any of the Wiki pages.

Can you please tell me how to do that?

### CODE REVIEW

**Comment by icyflame** [comment]
ping @amrav

**Comment by DefCon-007** [comment]
It's way too old @icyflame , should we merge it close it ?

**Comment by thealphadollar** [comment]
@icyflame @DefCon-007 Status?

**Comment by thealphadollar** [comment]
I'm closing this PR since it is stale.

**Pull request closed without merging**
